config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
      member do
        get "like", to: "posts#up_vote"
        get "dislike", to: "posts#down_vote"
      end
      resources :comments
  end
 
 root 'posts#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
    has_many :comments
    has_attached_file :image, styles: { medium: "700x500>", small: "350x250>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
    
    acts_as_votable

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
   before_action :configure_permitted_parameters, if: :devise_controller?

   protected

   def configure_permitted_parameters
     devise_parameter_sanitizer.for(:sign_up) << :name
     devise_parameter_sanitizer.for(:account_update) << :name
   end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    before_action :authenticate_user!
    
   
    
    def create
        @post = Post.find(params[:post_id])
        @comment = Comment.create(params[:comment].permit(:content))
        @comment.user_id = current_user.id
        @comment.post_id = @post.id
        if @comment.save
            redirect_to @post
        else 
            render 'new'
        end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    
    before_action :find_post, only: [:update,:edit,:destroy,:show,:up_vote,:down_vote]
    before_action :authenticate_user!, except: [:index,:show]
     def index
         @posts = Post.all
     end
     
     def new
         @post = current_user.posts.build
     end
     
     def create
         @post = current_user.posts.build(post_params)
         if @post.save
             redirect_to @post
         else
             render 'new'
         end
     end
     
     def update
         if @post.update(post_params)
             redirect_to @post
         else
             render 'edit'
         end
     end
     
     def edit
     end
     
     def destroy
         if @post.destroy
             redirect_to root_path
         else
             render 'edit'
         end
     end
     
     def up_vote
         @post.upvote_by current_user
         redirect_to :back
     end
     
     def down_vote
         @post.downvote_by current_user
         redirect_to :back
     end
     
     def show
         @comments = @post.comments
     end
     
     private
     
     def find_post
         @post=Post.find(params[:id])
     end
     
     def post_params
         params.require(:post).permit(:title,:link,:description,:image)
     end
     
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.haml
=simple_form_for([@post,@post.comments.build]) do |f|
    = f.input :content, label: "Reply to thread"
    = f.button :submit, class:"button"
    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Muse</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>
<%= yield %>

</body>
</html>

app/views/layouts/application.html.haml
!!!
%html
%head
    %title Muse
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true 
    = javascript_include_tag 'application', 'data-turbolinks-track' => true 
    = csrf_meta_tags 

%body
    .header
        .wrapper.clearfix
        #logo= link_to "Muse", root_path
        %nav
            - if user_signed_in?
                =link_to current_user.name, edit_user_registration_path
                =link_to "Add new inspiration", new_post_path, class:"button"
            - else
                =link_to sign_in, new_user_session_path
                =link_to sign_up, new_user_registration_path, class:"button"
    %p.notice= notice 
    %p.alert= alert
    = yield 

app/views/posts/_form.html.haml
=simple_form_for @post do |f|
    =f.input :image
    =f.input :title
    =f.input :link
    =f.input :description
    =f.button :submit

app/views/posts/edit.html.haml
%h1 Edit Post

=render 'form'

app/views/posts/index.html.haml
%h1 All Posts

-@posts.each do |post|
    %h2=link_to post.title, post_path(post)
    %h3= comment_count = pluralize(post.comments.count,"Count")
    = link_to image_tag(post.image.url(:small))
    %p=link_to 'check it out',post.link
    %p= post.description
    %p="upvote: #{post.get_upvotes.size}"
    %p="downvote: #{post.get_downvotes.size}"
=link_to 'add a new post',new_post_path

app/views/posts/new.html.haml
%h1 add new inspirations

= render 'form' 

app/views/posts/show.html.haml
%h1=@post.title
=image_tag @post.image.url(:medium)
%p=@post.link
%p=@post.description
%p="author- #{@post.user.name}"
="up votes #{@post.get_upvotes.size}"
="down votes #{@post.get_downvotes.size}"
=link_to 'vote up', like_post_path(@post), method: :get
=link_to 'down vote', dislike_post_path(@post), method: :get
#comment
    %h2= comment_count = pluralize(@post.comments.count,"Count")
   
    -@comments.each do |comment|
        .comment
            %p=comment.user.name
            %p.content=comment.content
            
    =render 'comments/form'

=link_to 'edit', edit_post_path(@post)
=link_to 'destroy', post_path(@post), method: :delete, data: {confirm: "Are you sure?"}
=link_to 'home',root_path